export { default as Education } from './Education'
export { default as HeaderInfo } from './HeaderInfo'
export { default as Languages } from './Languages'
export { default as Skills } from './Skills'
export { default as WorkExperience } from './WorkExperience/'
